spring:
  datasource:
    #url: jdbc:sqlserver://localhost:1433;databaseName=controlPedidos
    #username: mps
  #password: Aaa123456

    #hibernate:
    #dialect: org.hibernate.dialect.SQLServer2019Dialect


  #spring:
  #datasource:
    url: jdbc:mysql://localhost:3306/controlPedidos
    username: root
    password: 1234

  #url: jdbc:mysql://localhost:3306/controlPedidos
    #username: root
    #password: 1234
  #username: mps
  #password: Aaa123456
  #username: hp
  #password: Peras1234


  #LAPTOP-VI63ACQS\MSSQLSERVER2

#mysql

jpa:
  hibernate:
    ddl-auto: update


servlet:
  multipart:
    enabled: true
    max-file-size: 999MB
    max-request-size: 1224MB


  application:
    name: mpspedidosback


server:
  port: 8083

    #ssl:
    #key-store: classpath:ssl/ssl-certificate.p12
    #key-store-password: 4610450
  #key-store-type: PKCS12

  address=0.0.0.0:


datasource:
  username: "freelancerjulopez@gmail.com"
  password: "jzed gwlu gbds pxiv"


